pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '/usr/local/maven/bin/mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh '/usr/local/maven/bin/mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
          steps {
              script {
            def name = sh(script: "mvn -q -DforceStdout help:evaluate -Dexpression=project.name | sed -E 's/\\x1B\\[[0-9;]*[mK]//g'", returnStdout: true).trim()
            def version = sh(script: "mvn -q -DforceStdout help:evaluate -Dexpression=project.version | sed -E 's/\\x1B\\[[0-9;]*[mK]//g'", returnStdout: true).trim()
            
            echo "Running: target/${name}-${version}.jar"
            sh "java -jar target/${name}-${version}.jar"
                }
               }
        }

    }
}
